import {
	Box,
	Button,
	Card,
	CardActions,
	CardContent,
	CardMedia,
	Typography,
} from '@mui/material'
import * as React from 'react'
import { getProjectDatasets } from '../../api/projects'
import { BIDSDataset, HIPProject } from '../../api/types'
import { useAppStore } from '../../store/appProvider'
import { useNavigate, useParams } from 'react-router-dom'
import { ROUTE_PREFIX } from '../../constants'

const ProjectDashboard = () => {
	const navigate = useNavigate()
	const params = useParams()

	const [datasets, setDatasets] = React.useState<
		{ data?: BIDSDataset[]; error?: string } | undefined
	>()
	const [project, setProject] = React.useState<HIPProject>()

	const {
		user: [user],
		hIPProjects: [projects],
	} = useAppStore()

	React.useEffect(() => {
		if (!user?.uid) return
		getProjectDatasets(user?.uid).then(datasets => {
			setDatasets({ data: datasets })
		})
	}, [user?.uid])


	React.useEffect(() => {
		const project = projects?.find(project => project.id === params?.id)
		setProject(project)
	}, [projects, setProject, params])

	return (
		<Box>
			<Box sx={{ display: 'flex', justifyContent: 'start', gap: '16px 16px' }}>
				<Card
					sx={{
						width: 320,
					}}
				>
					<Box sx={{ position: 'relative' }}>
						<CardMedia
							component='img'
							height='160'
							src={`${process.env.REACT_APP_GATEWAY_API}/public/media/2825956551_neural_pathway__medical__futuristic__lots_of_neurons_and_dendrites__human__photo_realistic__picture_of_the_day.png`}
							title={
								'Image generated by DreamStudio, Text-to-Image Generative Art, https://beta.dreamstudio.ai/dream'
							}
						/>
					</Box>
					<CardContent>
						<Typography sx={{ mb: 2 }} variant='h5'>
							Members
						</Typography>
					</CardContent>
					<CardActions sx={{ p: 2 }}>
						<Button variant='outlined'>Add Member</Button>
					</CardActions>
				</Card>

				<Card
					sx={{
						width: 320,
					}}
					key={`data-group`}
				>
					<CardMedia
						component='img'
						height='160'
						title={
							'Image generated by DreamStudio, Text-to-Image Generative Art, https://beta.dreamstudio.ai/dream'
						}
						src={`${process.env.REACT_APP_GATEWAY_API}/public/media/1375898092_synapses__data___database__information__network__neural_path__futuristic_and_medical__realistic__8k__pic_of_the_day.png`}
					/>

					<CardContent>
						<Typography variant='h5'>Data</Typography>
					</CardContent>
					<CardActions sx={{ p: 2 }}>
						{datasets?.data?.map(dataset => (
							<Box key={dataset.id}>
								<Typography>{dataset.Name}</Typography>
								<Button
									onClick={() => {
										navigate(`${ROUTE_PREFIX}/collaborative-projects/${project?.id}/datasets/${dataset.id}`)
									}}
									variant='outlined'
								>
									Copy Files
								</Button>
							</Box>
						))}
					</CardActions>
				</Card>
			</Box>
		</Box>
	)
}

export default ProjectDashboard
