import * as React from 'react'
import {
	Box,
	Button,
	Card,
	CardContent,
	CardMedia,
	CircularProgress,
	Paper,
	Typography,
} from '@mui/material'
import {
	BIDSDataset,
	Container,
	HIPProject,
	InspectResult,
} from '../../api/types'
import { useEffect, useState } from 'react'
import { getProjectMetadataTree } from '../../api/projects'
import { API_GATEWAY } from '../../api/gatewayClientAPI'
import { useNotification } from '../../hooks/useNotification'
import path from 'path'
import FileBrowser from '../UI/FileBrowser'
import ProjectMetadataBrowser from '../UI/ProjectMetadataBrowser'

const Data = ({
	project,
	bidsDatasets,
	sessions,
}: {
	project?: HIPProject
	bidsDatasets?: {
		data?: BIDSDataset[] | undefined
		error?: string | undefined
	}
	sessions?: Container[]
}) => {
	const { showNotif } = useNotification()

	const [initialRender, setInitialRender] = useState(true)
	const [files, setFiles] = useState<InspectResult>()
	const [path, setPath] = useState<string>('/')
	const [selectedFile, setSelectedFile] = useState<string>()
	const [projectName, setProjectName] = useState<string | undefined>()

	useEffect(() => {
		if (projectName !== project?.name) {
			setInitialRender(true)
			setFiles(undefined)
		}
		setProjectName(project?.name)
	}, [project, setProjectName])

	useEffect(() => {
		if (initialRender && project) {
			setInitialRender(false)
			getProjectMetadataTree(project.name).then(f => setFiles(f))
		}
	}, [initialRender, project])

	return (
		<>
			{!bidsDatasets && (
				<CircularProgress
					size={32}
					color='secondary'
					sx={{ position: 'absolute', top: 10, left: 10 }}
				/>
			)}

			<Card
				sx={{
					width: 320,
				}}
				key={`data-group`}
			>
				<CardMedia
					component='img'
					height='160'
					title={
						'Image generated by DreamStudio, Text-to-Image Generative Art, https://beta.dreamstudio.ai/dream'
					}
					src={`${API_GATEWAY}/public/media/1907438463_synapses__technology__meta___database__information__network__neural_path__futuristic_and_medical__re.png`}
				/>

				<CardContent>
					<Typography variant='h5'>
						Files Metadata {!files && <CircularProgress size={12} />}
					</Typography>

					<Typography
						sx={{ mt: 2 }}
						gutterBottom
						variant='body2'
						color='text.secondary'
					>
						Private space for your center data.
					</Typography>
					<Box>
						<Box
							sx={{
								display: 'flex',
								flexWrap: 'wrap',
								gap: '16px 16px',
								mt: 2,
							}}
						>
							<Box elevation={2} component={Paper} sx={{ p: 1, flex: '1 0' }}>
								{path && (
									<ProjectMetadataBrowser
										files={files}
										selectedFile={setSelectedFile}
									/>
								)}
							</Box>
						</Box>
					</Box>
				</CardContent>
			</Card>
		</>
	)
}

export default Data
