import {
	Box, Card,
	CardContent,
	CardMedia,
	CircularProgress,
	Paper,
	Typography
} from '@mui/material'
import { useEffect, useState } from 'react'
import { API_GATEWAY } from '../../api/gatewayClientAPI'
import { getProjectMetadataTree } from '../../api/projects'
import {
	HIPProject,
	InspectResult
} from '../../api/types'
import { useNotification } from '../../hooks/useNotification'
import ProjectMetadataBrowser from '../UI/ProjectMetadataBrowser'
import * as React from 'react'

const Data = ({
	project,
}: {
	project?: HIPProject
}) => {
	const { showNotif } = useNotification()
	const [initialRender, setInitialRender] = useState(true)
	const [files, setFiles] = useState<InspectResult>()
	const [projectName, setProjectName] = useState<string | undefined>()

	useEffect(() => {
		if (projectName !== project?.name) {
			setInitialRender(true)
			setFiles(undefined)
		}
		setProjectName(project?.name)
	}, [project, setProjectName])

	useEffect(() => {
		if (initialRender && project) {
			setInitialRender(false)
			getProjectMetadataTree(project.name).then(f => setFiles(f))
		}
	}, [initialRender, project])

	return (
			<Card
				sx={{
					width: 320,
				}}
				key={`data-group`}
			>
				<CardMedia
					component='img'
					height='160'
					title={
						'Image generated by DreamStudio, Text-to-Image Generative Art, https://beta.dreamstudio.ai/dream'
					}
					src={`${API_GATEWAY}/public/media/1907438463_synapses__technology__meta___database__information__network__neural_path__futuristic_and_medical__re.png`}
				/>

				<CardContent>
					<Typography variant='h5'>
						Files Metadata {!files && <CircularProgress size={12} />}
					</Typography>

					<Typography
						sx={{ mt: 2 }}
						gutterBottom
						variant='body2'
						color='text.secondary'
					>
						Private space for your center data.
					</Typography>
					<Box>
						<Box
							sx={{
								display: 'flex',
								flexWrap: 'wrap',
								gap: '16px 16px',
								mt: 2,
							}}
						>
							<Box elevation={2} component={Paper} sx={{ p: 1, flex: '1 0' }}>
									<ProjectMetadataBrowser
										files={files}
									/>
							</Box>
						</Box>
					</Box>
				</CardContent>
			</Card>
	)
}

export default Data
