import {
	Box,
	Button,
	Card,
	CardMedia,
	Paper,
	Tab,
	Tabs,
	Typography,
} from '@mui/material'
import * as React from 'react'
import { useEffect, useState } from 'react'
import { API_GATEWAY } from '../../api/gatewayClientAPI'
import { getProjectMetadataTree, importBIDSSubject } from '../../api/projects'
import { InspectResult } from '../../api/types'
import { useAppStore } from '../../Store'
import FileBrowser from '../UI/FileBrowser'
import MetadataBrowser from '../UI/MetadataBrowser'
import TitleBar from '../UI/titleBar'

const Data = () => {
	const {
		user: [user],
		selectedProject: [selectedProject],
	} = useAppStore()
	const [files, setFiles] = useState<InspectResult>()
	const [tabIndex, setTabIndex] = useState(0)
	const [path, setPath] = useState<string>('/')
	const [selectedFile, setSelectedFile] = useState<string>()

	useEffect(() => {
		if (selectedProject) {
			getProjectMetadataTree(selectedProject.name).then(f => setFiles(f))
		}
	}, [selectedProject])

	const importDocument = () => {
		importBIDSSubject(
			{ datasetPath: '', subjectId: '' },
			selectedProject?.name || ''
		)
	}

	return (
		<Box sx={{ mb: 2 }}>
			<TitleBar title={`Files: ${selectedProject?.title || ''} `} />

			<Box sx={{ mt: 2 }}>
				<Box elevation={2} component={Paper} sx={{ mt: 2, mb: 2 }}>
						<CardMedia
							component='img'
							height='160'
							title={
								'Image generated by DreamStudio, Text-to-Image Generative Art, https://beta.dreamstudio.ai/dream'
							}
							src={`${API_GATEWAY}/public/media/1907438463_synapses__technology__meta___database__information__network__neural_path__futuristic_and_medical__re.png`}
						/>
				</Box>

				<Tabs
					value={tabIndex}
					onChange={(event: React.SyntheticEvent, newValue: number) =>
						setTabIndex(newValue)
					}
					aria-label='Matadata tabs'
				>
					<Tab label='Files' id={'tab-1'} />
					<Tab label='Transfer Files' id={'tab-2'} />
				</Tabs>

				{tabIndex === 0 && (
					<Box sx={{ mt: 2 }}>
						<Box elevation={2} component={Paper} sx={{ p: 1, flex: '1 0' }}>
							<Typography variant='h6'>Files</Typography>
							<Box
								sx={{
									display: 'flex',
									flexWrap: 'wrap',
									gap: '16px 16px',
									mt: 2,
								}}
							>
								<MetadataBrowser files={files} />
							</Box>
						</Box>
					</Box>
				)}

				{tabIndex === 1 && (
					<Box sx={{ mt: 2 }}>
						<Typography variant='h6'>Transfer Files</Typography>
						<Box
							sx={{
								display: 'flex',
								flexWrap: 'wrap',
								gap: '16px 16px',
								alignItems: 'start',
								mt: 2,
							}}
						>
							<Box elevation={2} component={Paper} sx={{ p: 1, flex: '1 0' }}>
								<Typography gutterBottom variant='h6' component='div'>
									My Files
								</Typography>
								{path && (
									<FileBrowser
										path={path}
										selectedFile={setSelectedFile}
										showSearch={true}
									/>
								)}
							</Box>
							<Button
								sx={{ my: 0.5 }}
								variant='outlined'
								size='small'
								aria-label='move selected right'
								onClick={importDocument}
							>
								&gt;
							</Button>
							<Box elevation={2} component={Paper} sx={{ p: 1, flex: '1 0' }}>
								<Typography gutterBottom variant='h6' component='div'>
									Project Files
								</Typography>
								<MetadataBrowser files={files} />
							</Box>
						</Box>
					</Box>
				)}
			</Box>
		</Box>
	)
}

export default Data
