import { Box, CardMedia, Paper, Typography } from '@mui/material'
import React, { useEffect, useState } from 'react'
import { API_GATEWAY } from '../../api/gatewayClientAPI'
import { getProjectMetadataTree } from '../../api/projects'
import { InspectResult } from '../../api/types'
import { useAppStore } from '../../Store'
import MetadataBrowser from '../UI/MetadataBrowser'
import TitleBar from '../UI/titleBar'

const Data = () => {
	const {
		selectedProject: [selectedProject],
	} = useAppStore()
	const [files, setFiles] = useState<InspectResult>()

	useEffect(() => {
		if (selectedProject) {
			getProjectMetadataTree(selectedProject.name).then(f => setFiles(f))
		}
	}, [selectedProject])

	return (
		<Box sx={{ mb: 2 }}>
			<TitleBar title={`Files: ${selectedProject?.title.replace(/-/g, ' ') || ''} `} />

			<Box sx={{ mt: 2 }}>
				<Box elevation={2} component={Paper} sx={{ mt: 2, mb: 2 }}>
					<CardMedia
						component='img'
						height='160'
						title={
							'Image generated by DreamStudio, Text-to-Image Generative Art, https://beta.dreamstudio.ai/dream'
						}
						src={`${API_GATEWAY}/public/media/3281435885_dendrites__technology__meta___database__information__network__neural_path__futuristic_and_medical__r.png`}
					/>
				</Box>

				<Box sx={{ mt: 2 }}>
					<Box elevation={2} component={Paper} sx={{ p: 1, flex: '1 0' }}>
						<Typography variant='h6'>
							{selectedProject?.title.replace(/-/g, ' ') || ''} Files
						</Typography>

						<Box
							sx={{
								display: 'flex',
								flexWrap: 'wrap',
								gap: '16px 16px',
								mt: 2,
							}}
						>
							<MetadataBrowser files={files} />
						</Box>
					</Box>

					<Typography sx={{ mt: 2, mb: 2 }}>
						You are currently viewing the metadata of the project file tree
						hierarchy because the content within the files is private in nature.
						The metadata provides information about the files, but does not
						disclose the actual content contained within. This is done to
						maintain the privacy and security of the information within the
						files.
					</Typography>
				</Box>
			</Box>
		</Box>
	)
}

export default Data
