import * as React from 'react'
import {
	Box,
	Button,
	Card,
	CardActions,
	CardContent,
	CardMedia,
	CircularProgress,
	FormControl,
	IconButton,
	InputLabel,
	MenuItem,
	Select,
	SelectChangeEvent,
	Stack,
	Typography,
} from '@mui/material'
import { Clear } from '@mui/icons-material'
import { HIPProject, User } from '../../api/types'
import { API_GATEWAY } from '../../api/gatewayClientAPI'
import UserInfo from '../UI/UserInfo'
import { useAppStore } from '../../Store'

interface Props {
	project?: HIPProject | null
	users?: User[]
	handleAddUserToProject: (userId: string) => void
	handleRemoveUserFromProject: (userId: string) => void
}

const MemberCard = ({
	project,
	users,
	handleAddUserToProject,
	handleRemoveUserFromProject,
}: Props) => {
	const [userToAdd, setUserToAdd] = React.useState('')
	const {
		user: [user],
	} = useAppStore()
	return (
		<>
			{project && (
				<Card
					sx={{
						display: 'flex',
						width: 320,
						flexDirection: 'column',
					}}
					key={`members-${project.name}`}
				>
					<Box sx={{ position: 'relative' }}>
						<CardMedia
							component='img'
							height='160'
							src={`${API_GATEWAY}/public/media/651069478_synapses__technology__meta___database__information__network__neural_path__futuristic_and_medical__re.png`}
							alt={project.title}
							title={
								'Image generated by DreamStudio, Text-to-Image Generative Art, https://beta.dreamstudio.ai/dream'
							}
						/>
					</Box>
					<CardContent>
						<Typography sx={{ mb: 2 }} variant='h5'>
							Members
						</Typography>

						{users === undefined && (
							<CircularProgress
								size={16}
								color='secondary'
								sx={{ top: 10, left: 10 }}
							/>
						)}

						<Stack spacing={1}>
							{project?.members?.length === 0 && (
								<Typography variant='subtitle2'>No members yet</Typography>
							)}

							{[...(project?.members || [])]
								.map(
									u =>
										users?.find(user => user.id === u) || {
											id: u,
											name: u,
											displayName: u,
										}
								)
								.map(u => (
									<Box
										key={u.id}
										display='flex'
										justifyContent='space-between'
										alignItems='center'
									>
										<UserInfo key={u.id} user={u} />
										{user?.uid && project?.admins?.includes(user.uid) && (
											<IconButton onClick={() => handleRemoveUserFromProject(u.id)}>
												<Clear />
											</IconButton>
										)}
									</Box>
								))}
						</Stack>
					</CardContent>
					<CardActions sx={{ p: 2 }}>
						{user?.uid && project?.admins?.includes(user.uid) && (
							<Box
								display='flex'
								justifyContent='space-between'
								alignItems='center'
							>
								<FormControl sx={{ m: 1, minWidth: 180 }}>
									<InputLabel variant='outlined'>Select</InputLabel>
									<Select
										size={'small'}
										//defaultValue={numberOfResultsPerPage}
										onChange={(event: SelectChangeEvent<string>) => {
											setUserToAdd(event.target.value)
										}}
									>
										{users?.map(user => (
											<MenuItem key={user.id} value={user.id}>
												{user.displayName}
											</MenuItem>
										))}
									</Select>
								</FormControl>

								<Button
									onClick={() => handleAddUserToProject(userToAdd)}
									variant='outlined'
								>
									Add
								</Button>
							</Box>
						)}
					</CardActions>
				</Card>
			)}
		</>
	)
}

export default MemberCard
