import {
	Box, Card,
	CardContent,
	CardMedia,
	CircularProgress,
	Paper,
	Typography
} from '@mui/material'
import { useParams } from 'react-router-dom'
import { API_GATEWAY } from '../../api/gatewayClientAPI'
import { getProjectMetadataTree } from '../../api/projects'
import {
	HIPProject,
	InspectResult
} from '../../api/types'
import { useNotification } from '../../hooks/useNotification'
import { useAppStore } from '../../Store'
import ProjectMetadataBrowser from '../UI/ProjectMetadataBrowser'
import React, { useEffect, useState } from 'react'

const Data = ({
	project,
}: {
	project?: HIPProject
}) => {
	const params = useParams()
	const { showNotif } = useNotification()
	const {
		containers: [containers],
		BIDSDatasets: [bidsDatasets],
		user: [user],
		projects: [projects, setProjects],
	} = useAppStore()
	const [initialRender, setInitialRender] = useState(true)
	const [files, setFiles] = useState<InspectResult>()
	const [projectName, setProjectName] = useState<string | undefined>()

	useEffect(() => {
		const project = projects?.find(
			project => project.name === params?.projectId
		)
		if (projectName !== project?.name) {
			setInitialRender(true)
			setFiles(undefined)
		}
		setProjectName(project?.name)
	}, [project, setProjectName])

	useEffect(() => {
		const project = projects?.find(
			project => project.name === params?.projectId
		)
		if (initialRender && project) {
			setInitialRender(false)
			getProjectMetadataTree(project.name).then(f => setFiles(f))
		}
	}, [initialRender, project])

	return (
			<Card>
				<CardMedia
					component='img'
					height='160'
					title={
						'Image generated by DreamStudio, Text-to-Image Generative Art, https://beta.dreamstudio.ai/dream'
					}
					src={`${API_GATEWAY}/public/media/1907438463_synapses__technology__meta___database__information__network__neural_path__futuristic_and_medical__re.png`}
				/>

				<CardContent>
					<Typography variant='h5'>
						Project Files Metadata {!files && <CircularProgress size={12} />}
					</Typography>

					<Box component={Paper} sx={{ p: 1 }}>
						<ProjectMetadataBrowser
							files={files}
						/>
					</Box>
				</CardContent>
			</Card>
	)
}

export default Data
