default:
  image: node:17
  before_script:
    - apt update && apt install -y gettext
    - npm install -g react-scripts typescript --silent

stages:
  - test
  - build
  - release

test_:
  stage: test
  script: 
  - make test

build:
  stage: build
  script:
    - make build

release:
  stage: release
  script:
    - make release
