import {
	Box,
	Button,
	Card,
	CardContent,
	CardMedia,
	CircularProgress,
	TextareaAutosize,
	Typography,
} from '@mui/material'
import * as React from 'react'
import { API_GATEWAY, scanUserFiles } from '../../../api/gatewayClientAPI'
import { useAppStore } from '../../../Store'

const Tools = () => {
	const {
		user: [user],
	} = useAppStore()

	const [scanning, setScanning] = React.useState(false)
	const [scanResult, setScanResult] = React.useState('')

	const scanFiles = async () => {
		if (!user) return
		setScanning(true)
		const res = await scanUserFiles(user.uid || '')
		setScanResult(res)
		setScanning(false)
	}

	// const setWorkspace = async () => {
	// 	if (!user) return
	// 	setScanning(true)
	// 	const res = await setNCWorkspace(user.uid || '')
	// 	setScanResult(res)
	// 	setScanning(false)
	// }

	return (
		<>
			<Card
				sx={{
					width: 320,
					height: 440,
				}}
				key={`center-tools`}
			>
				<CardMedia
					component='img'
					height='160'
					src={`${API_GATEWAY}/public/media/hospital-tools.png`}
					alt={'tools'}
					title={
						'Image generated by DreamStudio, Text-to-Image Generative Art, https://beta.dreamstudio.ai/dream'
					}
				/>

				<CardContent>
					<Typography variant='h5'>Tools</Typography>

					<Typography
						sx={{ mt: 2 }}
						gutterBottom
						variant='body2'
						color='text.secondary'
					>
						Perform a files scan to synchronize the backend storage with the
						interface
					</Typography>
					<Box
						sx={{
							display: 'flex',
							justifyContent: 'space-between',
							alignItems: 'center',
						}}
					>
						<Button onClick={scanFiles}>Scan files</Button>
						{/* <Button onClick={setWorkspace}>NC prefs</Button> */}
						{scanning && (
							<CircularProgress
								size={16}
								color='secondary'
								sx={{ top: 10, left: 10 }}
							/>
						)}
					</Box>

					<TextareaAutosize
						aria-label='scan result textarea'
						style={{ width: 290 }}
						defaultValue={scanResult}
					/>
				</CardContent>
			</Card>
		</>
	)
}

export default Tools
