import * as React from 'react'
import { Chat } from '@mui/icons-material'
import {
	Box,
	Card,
	CardContent,
	CardMedia,
	CircularProgress,
	IconButton,
	Stack,
	Typography,
} from '@mui/material'
import { HIPGroup, User } from '../../api/types'

const Members = ({ group, users }: { group?: HIPGroup; users?: User[] }) => {
	return (
		<>
			{group && (
				<Card
					sx={{
						display: 'flex',
						width: 320,
						flexDirection: 'column',
					}}
					key={`members-${group.label}`}
				>
					<Box sx={{ position: 'relative' }}>
						<CardMedia
							component='img'
							height='160'
							src={`${process.env.REACT_APP_GATEWAY_API}/public/media/2825956551_neural_pathway__medical__futuristic__lots_of_neurons_and_dendrites__human__photo_realistic__picture_of_the_day.png`}
							alt={group.label}
							title={
								'Image generated by DreamStudio, Text-to-Image Generative Art, https://beta.dreamstudio.ai/dream'
							}
						/>
					</Box>
					<CardContent>
						<Typography sx={{ mb: 2 }} variant='h5'>
							Members
						</Typography>

						{users === undefined && (
							<CircularProgress
								size={16}
								color='secondary'
								sx={{ top: 10, left: 10 }}
							/>
						)}

						<Stack spacing={1}>
							{users?.length === 0 && (
								<Typography variant='subtitle2'>No members yet</Typography>
							)}
							{users?.map(user => (
								<Box
									key={user.id}
									sx={{
										display: 'flex ',
										gap: 2,
										justifyContent: 'space-between',
									}}
								>
									<Stack>
										<Typography variant='subtitle2'>
											{user.displayName}
										</Typography>
										<Typography color='text.secondary' variant='body2'>
											{user.email}
										</Typography>
									</Stack>

									<IconButton
										color='primary'
										onClick={() => {
											window.open(`/u/${user.id}`, '_blank')
										}}
										aria-label={`Chat with ${user.displayName}`}
									>
										<Chat />
									</IconButton>
								</Box>
							))}
						</Stack>
					</CardContent>
				</Card>
			)}
		</>
	)
}

export default Members
