import * as React from 'react'
import {
	Box,
	Card,
	CardContent,
	CardMedia,
	CircularProgress,
	Stack,
	Typography,
} from '@mui/material'
import { API_GATEWAY } from '../../api/gatewayClientAPI'
import { HIPCenter, User } from '../../api/types'
import UserInfo from '../UI/UserInfo'

const Members = ({ group, users }: { group?: HIPCenter; users?: User[] }) => {
	return (
		<>
			{group && (
				<Card
					sx={{
						display: 'flex',
						width: 320,
						flexDirection: 'column',
					}}
					key={`members-${group.label}`}
				>
					<Box sx={{ position: 'relative' }}>
						<CardMedia
							component='img'
							height='160'
							src={`${API_GATEWAY}/public/media/hospital-staff-members.png`}
							alt={group.label}
							title={
								'Image generated by DreamStudio, Text-to-Image Generative Art, https://beta.dreamstudio.ai/dream'
							}
						/>
					</Box>
					<CardContent>
						<Typography sx={{ mb: 2 }} variant='h5'>
							Members
						</Typography>

						{users === undefined && (
							<CircularProgress
								size={16}
								color='secondary'
								sx={{ top: 10, left: 10 }}
							/>
						)}
						<Stack
							spacing={1}
							sx={{
								maxHeight: 190,
								display: 'flex',
								flexDirection: 'column',
								overflowY: 'scroll',
							}}
						>
							{users?.length === 0 && (
								<Typography variant='subtitle2'>No members yet</Typography>
							)}
							{users?.map(user => (
								<UserInfo key={user.id} user={user} />
							))}
						</Stack>
					</CardContent>
				</Card>
			)}
		</>
	)
}

export default Members
