name: Makefile CI

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:

    runs-on: node:17

    steps:
    - uses: actions/checkout@v3
      
    - name: Run build
      run: make build
      
    - name: Run release
      run: make release
